src/main/java/fr/uga/miashs/sempic/entities/SempicPicture.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.miashs.sempic.entities;

import java.nio.file.Paths;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import fr.uga.miashs.sempic.SempicException;
import fr.uga.miashs.sempic.dao.PhotoStorage;
import java.io.IOException;
import java.io.Serializable;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Temporal;
import javax.validation.constraints.NotBlank;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 *
 * @author marty
 */
@Entity
@NamedQueries({
    @NamedQuery(
            name="query.SempicPicture.findAllOwned",
            query="SELECT p FROM SempicPicture p Join p.album a WHERE a.owner=:owner"),
    @NamedQuery(
            name = "query.SempicPicture.findAllOfAlbum",
            query = "SELECT p FROM SempicPicture p WHERE p.album=:album"),
    @NamedQuery(
            name = "query.SempicPicture.findAllPicturesFromIds",
            query = "SELECT p FROM SempicPicture p WHERE p.id IN :picturesIds"),})
public class SempicPicture implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    
    @ManyToOne
    private SempicAlbum album;

    @NotBlank(message = "Un nom de famille doit être donné")
    private String title;

    private String description;

    @LazyCollection(LazyCollectionOption.FALSE)
    @ElementCollection(targetClass = String.class)
    private List<String> places;

    @Temporal(javax.persistence.TemporalType.DATE)
    private Date date;

    @LazyCollection(LazyCollectionOption.FALSE)
    @ElementCollection(targetClass = String.class)
    private List<String> tags;

    @LazyCollection(LazyCollectionOption.FALSE)
    @ManyToMany
    private Set<SempicUser> usersTagged;
    
    public SempicPicture() {

    }

    public String getPicturePath() {
        return PhotoStorage.PICTURESTOREWEB.resolve(title).toString();
    }

    public String getThumbnailPath() throws SempicException {
        Path pic = Paths.get(title);

        try {
            PhotoStorage ps = new PhotoStorage(PhotoStorage.URLSTORE, PhotoStorage.URLTHUMBNAILSTORE);
            ps.getThumbnailPath(pic, 120);
            return PhotoStorage.buildAndVerify(PhotoStorage.THUMBNAILSSTOREWEB.resolve(String.valueOf(120)), pic).toString();
        } catch (IOException ex) {
            Logger.getLogger(SempicPicture.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";
    }

    public String getMediumPath() throws SempicException {
        Path pic = Paths.get(title);
        try {
            PhotoStorage ps = new PhotoStorage(PhotoStorage.URLSTORE, PhotoStorage.URLTHUMBNAILSTORE);
            ps.getThumbnailPath(pic, 400);
            return PhotoStorage.buildAndVerify(PhotoStorage.THUMBNAILSSTOREWEB.resolve(String.valueOf(400)), pic).toString();
        } catch (IOException ex) {
            Logger.getLogger(SempicPicture.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public SempicAlbum getAlbum() {
        return album;
    }

    public void setAlbum(SempicAlbum album) {
        if (album == null) {
            throw new NullPointerException("Album is null");
        }
        this.album = album;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<String> getPlaces() {
        if (places == null) {
            places = new ArrayList<>();
        }
        return places;
    }

    public void setPlaces(List<String> places) {
        this.places = places;
    }

    protected void addPlace(String place) {
        if (places == null) {
            places = new ArrayList<>();
        }
        places.add(place);
    }
    
    public List<String> getTags() {
        if (tags == null) {
            tags = new ArrayList<>();
        }
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Set<SempicUser> getUsersTagged() {
        return usersTagged;
    }

    public void setUsersTagged(Set<SempicUser> usersTagged) {
        this.usersTagged = usersTagged;
    }
    
   
    
    protected void addUsersTagged(SempicUser u) {
        if (usersTagged==null) {
            usersTagged = new HashSet<>();
        }
        usersTagged.add(u);
    }
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof SempicPicture)) {
            return false;
        }
        SempicPicture other = (SempicPicture) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "fr.uga.miashs.sempic.entities.SempicPicture[ id=" + id + " ]";
    }

}

src/main/java/fr/uga/miashs/sempic/backingbeans/AlbumController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.miashs.sempic.backingbeans;


import fr.uga.miashs.sempic.SempicException;
import fr.uga.miashs.sempic.SempicMessage;
import fr.uga.miashs.sempic.SempicModelException;
import fr.uga.miashs.sempic.SempicModelUniqueException;
import fr.uga.miashs.sempic.dao.AlbumFacade;
import fr.uga.miashs.sempic.dao.SempicUserFacade;
import fr.uga.miashs.sempic.entities.SempicAlbum;
import fr.uga.miashs.sempic.entities.SempicPicture;
import fr.uga.miashs.sempic.entities.SempicUser;
import fr.uga.miashs.sempic.rdf.AlbumStore;
import fr.uga.miashs.sempic.util.AccessRedirect;
import java.io.IOException;
import java.io.Serializable;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import javax.annotation.PostConstruct;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;


/**
 *
 * @author Jerome David <jerome.david@univ-grenoble-alpes.fr>
 */
@Named
@ViewScoped
public class AlbumController implements Serializable {

    private SempicAlbum current;

    @Inject
    private SessionTools session;
    
    @Inject
    private AlbumFacade albumDao;

    @Inject
    private SempicUserFacade userDao;
    
    private AlbumStore albumRdf;

    @Inject
    private PictureController pictureController;

    private DataModel<SempicAlbum> albums;
        
    public AlbumController() {
        userDao = new SempicUserFacade();
        albumDao = new AlbumFacade();
        albumRdf = new AlbumStore();
    }

    @PostConstruct
    public void init() {
        current = new SempicAlbum();
    }
    
    public void accessAlbum(ComponentSystemEvent event) throws IOException{
        if (current == null || (!current.getOwner().equals(session.getConnectedUser()) && !session.isAdmin())) {
          AccessRedirect.intance().redirectAccessDenied();
        }
    }
    
    public List<SempicUser> getUsers() {
        return userDao.findAll();
    }
    
    public void setOwnerId(String id) {
        current.setOwner(userDao.read(Long.valueOf(id)));
    }
    
    public String getOwnerId() {
        if (current.getOwner()==null)
            return "-1";
        return ""+current.getOwner().getId();
    }
    
    
    public void setAlbumId(String id) {
        current = albumDao.read(Long.valueOf(id));
    }

    public String getAlbumId() {
        if (current == null) {
            return "-1";
        }
        return "" + current.getId();
    }    
    public SempicAlbum getCurrent() {
        return current;
    }

    public void setCurrent(SempicAlbum current) {
        this.current = current;
    }
    
    public DataModel<SempicAlbum> getAlbums() throws SempicModelException {
        if (albums == null) {
            if (session.isAdmin()){
                albums = new ListDataModel<>(albumDao.findAll());
            }
            else {
                albums = new ListDataModel<>(albumDao.findAllOfOwner(session.getConnectedUser()));
            }
        }
        return albums;
    }
    
    public Set<SempicPicture> getPictures(){
            return current.getPictures();
    }
    
    public String create() {
        try {
            albumDao.create(current);
            albumRdf.createAlbum(current.getId(), current.getOwner().getId(), current.getTitle(), current.getDescription());
        } catch (SempicModelException ex) {
            SempicMessage.intance().errorMessage(ex.getMessage());
            return "failure";
        }
        SempicMessage.intance().successCreateMessage(current.toString());
        return "success";
    }
        
    
    public String update() {        
        try {
            albumDao.update(current);
        } 
        catch (SempicModelUniqueException ex) {
            SempicMessage.intance().errorMessage("Un album avec ce nom existe déjà");
            return "failure";
        }
        catch (SempicModelException ex) {
            SempicMessage.intance().errorMessage(ex.getMessage());
            return "failure";
        }
        SempicMessage.intance().successUpdateMessage(current.toString());
        return "success";
    }
    
    public String delete() throws IOException, SempicException {
        String text;
        Boolean fromList = false;
        try {
            if (current.getTitle() == null){
                fromList = true;
                current = (SempicAlbum) albums.getRowData();
            }
            text = current.toString();
            pictureController.deleteAllPicturesOfAlbum(current);
            current.setPictures(Collections.emptySet());
            albumRdf.deleteAlbum(current.getId());
            albumDao.delete(current);
            if (fromList) {
                albums.setWrappedData(albumDao.findAll());
            }
        } 
        catch (SempicModelException ex) {
            SempicMessage.intance().errorMessage(ex.getMessage());
            return "failure";
        }
        SempicMessage.intance().successDeleteMessage(text);	
        return "success";
    }
    
    public void deleteAllAlbumsOfUser(SempicUser user) throws IOException, SempicException {
        for (SempicAlbum album : user.getAlbums()) {
           current = album;
           delete();
        }
    }
  
}

src/main/java/fr/uga/miashs/sempic/backingbeans/UserController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.miashs.sempic.backingbeans;

import fr.uga.miashs.sempic.SempicException;
import fr.uga.miashs.sempic.SempicMessage;
import fr.uga.miashs.sempic.SempicModelException;
import fr.uga.miashs.sempic.SempicModelUniqueException;
import fr.uga.miashs.sempic.dao.SempicUserFacade;
import fr.uga.miashs.sempic.entities.SempicUser;
import fr.uga.miashs.sempic.rdf.UserStore;
import fr.uga.miashs.sempic.util.AccessRedirect;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotBlank;

/**
 *
 * @author Jerome David <jerome.david@univ-grenoble-alpes.fr>
 */
@Named
@ViewScoped
public class UserController implements Serializable {
    
    private SempicUser current;

    @Inject
    private SessionTools session;
    
    @Inject
    private AlbumController albumController;
    
    @Inject
    private SempicUserFacade userDao;
    
    private DataModel users;
    
    private UserStore userRdf;

    public UserController() {
        userDao = new SempicUserFacade();
    }
    
    public void accessUser(ComponentSystemEvent event) throws IOException{
        
        if (current == null || (!current.equals(session.getConnectedUser()) && !session.isAdmin())) {
          AccessRedirect.intance().redirectAccessDenied();
        }
    }
    
    @PostConstruct
    public void init() {
        current=new SempicUser();
        userRdf = new UserStore();
    }

    public String getTitle(String page) {
        String title;
        if (page.equals("update") && session.getConnectedUser().getId() != current.getId()) {
            title = "Modification utilisateur";
        }
        else {
            title = "Mon compte";
        }
        return title;
    }
    
    public List<SempicUser> getListUsers() {
        return userDao.findAll();
    }
    
    public SempicUser getCurrent() {
        return current;
    }

    public void setCurrent(SempicUser current) {
        this.current = current;
    }

    public void setUserId(String id) { 
        current = userDao.read(Long.valueOf(id));
    }
    
    public String getUserId() {
        if (current == null)
            return "-1";
        return ""+ current.getId();
    }
    
    
    public void setPassword(@NotBlank(message="Mot de passe est requis") String password) {
        getCurrent().setPassword(password);
    }
    
    public DataModel<SempicUser> getUsers() {
        if (users == null) {
            users = new ListDataModel<>(userDao.findAll());
        }
        return users;
    }
  
    public String create() {
        try {
            userDao.create(current);
            userRdf.createUser(current.getId(), current.getFirstname(), current.getLastname());
        } 
        catch (SempicModelUniqueException ex) {
            SempicMessage.intance().errorMessage("Un utilisateur avec cette adresse mail existe déjà");
            return "failure";
        }
        catch (SempicModelException ex) {
            SempicMessage.intance().errorMessage(ex.getMessage());
            return "failure";
        }
        SempicMessage.intance().successCreateMessage(current.getEmail());
        return "success";
    }
    
    public String update() {        
        try {
            userDao.update(current);
        } 
        catch (SempicModelUniqueException ex) {
            SempicMessage.intance().errorMessage("Un utilisateur avec cette adresse mail existe déjà");
            return "failure";
        }
        catch (SempicModelException ex) {
            SempicMessage.intance().errorMessage(ex.getMessage());
            return "failure";
        }
        if (session.isAdmin()){
            SempicMessage.intance().successUpdateMessage(current.getEmail());
            return "success_admin";
        }
        else {
            SempicMessage.intance().successUpdateAccountMessage();
            return "success_user"; 
        }

    }
    
    public String delete() throws IOException, SempicException {
        String text;
        Boolean fromList = false;
        try {
            if (current.getEmail() == null){
                fromList = true;
                current = (SempicUser) users.getRowData();
            }
            text = current.getEmail();
            albumController.deleteAllAlbumsOfUser(current);
            userRdf.deleteUser(current.getId());
            userDao.delete(current);
            if (fromList) {
                users.setWrappedData(userDao.findAll());
            }
        } 
        catch (SempicModelException ex) {
            SempicMessage.intance().errorMessage(ex.getMessage());
            return "failure";
        }
        if (session.isAdmin()){
            SempicMessage.intance().successDeleteMessage(current.getEmail());
            return "success_admin";
        }
        else {
            session.logout();
            SempicMessage.intance().successDeleteAccountMessage();
            return "success_user"; 
        }
    }
}

src/main/webapp/user/album/create-album.xhtml
<ui:composition template="/templates/layout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:h5="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    <f:metadata>
        <f:event listener="#{albumController.accessAlbum(event)}" type="preRenderView" />
        <f:viewParam name="userId" value="#{albumController.ownerId}" />
    </f:metadata>
    <ui:define name="title">Création album</ui:define>
    <ui:define name="content">
        <div class="row">
            <div class="col s6 offset-s3">
                <div class="card">
                    <div class="card-content">
                        <div class="left-align">
                            <h:form enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col s12 input-field">
                                        <h:inputText id="title" required="true" requiredMessage="Titre obligatoire" value="#{albumController.current.title}"/>
                                        <h:outputLabel for="title" value="Titre"  />
                                        <h:message for="title"/>
                                    </div>
                                    <div class="col s12 input-field">
                                        <h:inputText id="description" value="#{albumController.current.description}"/>
                                        <h:outputLabel for="description" value="Description" />
                                        <h:message for="description"/>
                                    </div>
                                    <div class="center-align col s12 input-field">
                                        <h:commandButton id="submit" class="btn btn-large" value="Créer" action="#{albumController.create}"/>
                                    </div>
                                </div>
                            </h:form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/user/album/list-albums.xhtml
<ui:composition template="/templates/layout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui/material">
    <ui:define name="title">Albums</ui:define>
    <ui:define name="content">
        <h:form rendered="#{not empty albumController.albums}">
            <div class="row">
                <div class="col s12">
                    <h:link class="btn-floating btn-card blue btn-large" outcome="create-album">
                        <f:param name="userId" value="#{sessionTools.connectedUser.id}"/>
                        <i class="small material-icons">add</i>
                    </h:link>
                </div>
            </div>
            <div class="row">
                <ui:repeat value="#{albumController.albums}" var="album">
                    <div class="col l4 m6 s12 gallery-item gallery-expand gallery-filter bigbang">
                        <div class="gallery-curve-wrapper">
                            <a class="gallery-cover gray">
                                <h:graphicImage class="responsive-img"  rendered="#{albumController.current.pictures.size() > 0}" value="#{albumController.current.pictures[0].mediumPath}" />
                                <img class="activator" src="#{resource['images/styles/default-thumbnail.jpg']}" rendered="#{albumController.current.pictures.size() == 0}"/>
                            </a>
                            <div class="gallery-header">
                                <span>#{album.title}</span>
                            </div>
                            <div class="gallery-body">
                                <h:link outcome="update-album" title="Modifier" class="btn-floating btn-card blue btn-large">
                                    <f:param name="albumId" value="#{album.id}"/>
                                    <i class="small material-icons">edit</i>
                                </h:link>
                                <h:commandLink action="#{albumController.delete}" title="Supprimer" class="btn-floating btn-card btn-large red">
                                    <i class="small material-icons icon-salmon">delete</i>
                                </h:commandLink>
                            </div>
                        </div>
                    </div>
                </ui:repeat>  
            </div>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/user/album/update-album.xhtml
<ui:composition template="/templates/layout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:h5="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    <f:metadata>
        <f:event listener="#{albumController.accessAlbum(event)}" type="preRenderView" />
        <f:viewParam name="albumId" value="#{albumController.albumId}" />
    </f:metadata>
    <ui:define name="title">Modification album</ui:define>
    <ui:define name="content">
        <div class="row">
            <div class="col s3">
                <div class="card">
                    <div class="card-content">
                        <div class="left-align">
                            <h:form enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col s12 input-field">
                                        <h:inputText id="title" required="true" requiredMessage="Titre obligatoire" value="#{albumController.current.title}"/>
                                        <h:outputLabel for="title" value="Titre"  />
                                        <p:message for="title"/>
                                    </div>
                                    <div class="col s12 input-field">
                                        <h:inputText id="description" value="#{albumController.current.description}"/>
                                        <h:outputLabel for="description" value="Description" />
                                        <p:message for="description"/>
                                    </div>
                                    <div class="center-align col s6 input-field">
                                        <h:commandLink class="btn-floating btn-card blue btn-large" title="Enregistrer" action="#{albumController.update}">
                                            <i class="medium material-icons">save</i>
                                        </h:commandLink>
                                    </div>
                                    <div class="center-align col s6 input-field">
                                        <h:link class="btn-floating btn-card teal btn-large" outcome="create-picture">
                                            <f:param name="albumId" value="#{albumController.current.id}"/>
                                            <i class="small material-icons">add_a_photo</i>
                                        </h:link>
                                    </div>
                                </div>
                            </h:form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col s9">
                <div id="portfolio" class="section gray">
                    <div class="container">
                        <div class="gallery row">
                            <ui:repeat value="#{albumController.current.pictures}" var="picture" rendered="#{not empty albumController.current.pictures}">
                                <div class="col l4 m6 s12 thumbnail">
                                    <h:graphicImage  value="#{picture.thumbnailPath}" />
                                    <h:link outcome="update-picture"  title="Modifier" class="btn-floating btn-card blue btn-large">
                                        <f:param name="pictureId" value="#{picture.id}"/>
                                        <i class="small material-icons">edit</i>
                                    </h:link>
                                </div>
                            </ui:repeat>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </ui:define>
</ui:composition>