src/main/java/fr/uga/miashs/sempic/entities/SempicPicture.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.miashs.sempic.entities;

import java.nio.file.Paths;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import fr.uga.miashs.sempic.SempicException;
import fr.uga.miashs.sempic.dao.PhotoStorage;
import java.io.IOException;
import java.io.Serializable;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Temporal;
import javax.validation.constraints.NotBlank;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 *
 * @author marty
 */
@Entity
@NamedQueries({
    @NamedQuery(
            name="query.SempicPicture.findAllOwned",
            query="SELECT p FROM SempicPicture p Join p.album a WHERE a.owner=:owner"),
    @NamedQuery(
            name = "query.SempicPicture.findAllOfAlbum",
            query = "SELECT p FROM SempicPicture p WHERE p.album=:album"),
    @NamedQuery(
            name = "query.SempicPicture.findAllPicturesFromIds",
            query = "SELECT p FROM SempicPicture p WHERE p.id IN :picturesIds"),})
public class SempicPicture implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    
    @ManyToOne
    private SempicAlbum album;

    @NotBlank(message = "Un nom de famille doit être donné")
    private String title;

    private String description;

    @LazyCollection(LazyCollectionOption.FALSE)
    @ElementCollection(targetClass = String.class)
    private List<String> places;

    @Temporal(javax.persistence.TemporalType.DATE)
    private Date date;

    @LazyCollection(LazyCollectionOption.FALSE)
    @ElementCollection(targetClass = String.class)
    private List<String> tags;

    @LazyCollection(LazyCollectionOption.FALSE)
    @ManyToMany
    private Set<SempicUser> usersTagged;
    
    public SempicPicture() {

    }

    public String getPicturePath() {
        return PhotoStorage.PICTURESTOREWEB.resolve(title).toString();
    }

    public String getThumbnailPath() throws SempicException {
        Path pic = Paths.get(title);

        try {
            PhotoStorage ps = new PhotoStorage(PhotoStorage.URLSTORE, PhotoStorage.URLTHUMBNAILSTORE);
            ps.getThumbnailPath(pic, 120);
            return PhotoStorage.buildAndVerify(PhotoStorage.THUMBNAILSSTOREWEB.resolve(String.valueOf(120)), pic).toString();
        } catch (IOException ex) {
            Logger.getLogger(SempicPicture.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";
    }

    public String getMediumPath() throws SempicException {
        Path pic = Paths.get(title);
        try {
            PhotoStorage ps = new PhotoStorage(PhotoStorage.URLSTORE, PhotoStorage.URLTHUMBNAILSTORE);
            ps.getThumbnailPath(pic, 400);
            return PhotoStorage.buildAndVerify(PhotoStorage.THUMBNAILSSTOREWEB.resolve(String.valueOf(400)), pic).toString();
        } catch (IOException ex) {
            Logger.getLogger(SempicPicture.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public SempicAlbum getAlbum() {
        return album;
    }

    public void setAlbum(SempicAlbum album) {
        if (album == null) {
            throw new NullPointerException("Album is null");
        }
        this.album = album;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<String> getPlaces() {
        if (places == null) {
            places = new ArrayList<>();
        }
        return places;
    }

    public void setPlaces(List<String> places) {
        this.places = places;
    }

    protected void addPlace(String place) {
        if (places == null) {
            places = new ArrayList<>();
        }
        places.add(place);
    }
    
    public List<String> getTags() {
        if (tags == null) {
            tags = new ArrayList<>();
        }
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Set<SempicUser> getUsersTagged() {
        return usersTagged;
    }

    public void setUsersTagged(Set<SempicUser> usersTagged) {
        this.usersTagged = usersTagged;
    }
    
   
    
    protected void addUsersTagged(SempicUser u) {
        if (usersTagged==null) {
            usersTagged = new HashSet<>();
        }
        usersTagged.add(u);
    }
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof SempicPicture)) {
            return false;
        }
        SempicPicture other = (SempicPicture) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "fr.uga.miashs.sempic.entities.SempicPicture[ id=" + id + " ]";
    }

}

src/main/java/fr/uga/miashs/sempic/backingbeans/UserController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.miashs.sempic.backingbeans;

import fr.uga.miashs.sempic.SempicException;
import fr.uga.miashs.sempic.SempicMessage;
import fr.uga.miashs.sempic.SempicModelException;
import fr.uga.miashs.sempic.SempicModelUniqueException;
import fr.uga.miashs.sempic.dao.SempicUserFacade;
import fr.uga.miashs.sempic.entities.SempicUser;
import fr.uga.miashs.sempic.rdf.UserStore;
import fr.uga.miashs.sempic.util.AccessRedirect;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotBlank;

/**
 *
 * @author Jerome David <jerome.david@univ-grenoble-alpes.fr>
 */
@Named
@ViewScoped
public class UserController implements Serializable {
    
    private SempicUser current;

    @Inject
    private SessionTools session;
    
    @Inject
    private AlbumController albumController;
    
    @Inject
    private SempicUserFacade userDao;
    
    private DataModel users;
    
    private UserStore userRdf;

    public UserController() {
        userDao = new SempicUserFacade();
    }
    
    public void accessUser(ComponentSystemEvent event) throws IOException{
        
        if (current == null || (!current.equals(session.getConnectedUser()) && !session.isAdmin())) {
          AccessRedirect.intance().redirectAccessDenied();
        }
    }
    
    @PostConstruct
    public void init() {
        current=new SempicUser();
        userRdf = new UserStore();
    }

    public String getTitle(String page) {
        String title;
        if (page.equals("update") && session.getConnectedUser().getId() != current.getId()) {
            title = "Modification utilisateur";
        }
        else {
            title = "Mon compte";
        }
        return title;
    }
    
    public List<SempicUser> getListUsers() {
        return userDao.findAll();
    }
    
    public SempicUser getCurrent() {
        return current;
    }

    public void setCurrent(SempicUser current) {
        this.current = current;
    }

    public void setUserId(String id) { 
        current = userDao.read(Long.valueOf(id));
    }
    
    public String getUserId() {
        if (current == null)
            return "-1";
        return ""+ current.getId();
    }
    
    
    public void setPassword(@NotBlank(message="Mot de passe est requis") String password) {
        getCurrent().setPassword(password);
    }
    
    public DataModel<SempicUser> getUsers() {
        if (users == null) {
            users = new ListDataModel<>(userDao.findAll());
        }
        return users;
    }
  
    public String create() {
        try {
            userDao.create(current);
            userRdf.createUser(current.getId(), current.getFirstname(), current.getLastname());
        } 
        catch (SempicModelUniqueException ex) {
            SempicMessage.intance().errorMessage("Un utilisateur avec cette adresse mail existe déjà");
            return "failure";
        }
        catch (SempicModelException ex) {
            SempicMessage.intance().errorMessage(ex.getMessage());
            return "failure";
        }
        SempicMessage.intance().successCreateMessage(current.getEmail());
        return "success";
    }
    
    public String update() {        
        try {
            userDao.update(current);
        } 
        catch (SempicModelUniqueException ex) {
            SempicMessage.intance().errorMessage("Un utilisateur avec cette adresse mail existe déjà");
            return "failure";
        }
        catch (SempicModelException ex) {
            SempicMessage.intance().errorMessage(ex.getMessage());
            return "failure";
        }
        if (session.isAdmin()){
            SempicMessage.intance().successUpdateMessage(current.getEmail());
            return "success_admin";
        }
        else {
            SempicMessage.intance().successUpdateAccountMessage();
            return "success_user"; 
        }

    }
    
    public String delete() throws IOException, SempicException {
        String text;
        Boolean fromList = false;
        try {
            if (current.getEmail() == null){
                fromList = true;
                current = (SempicUser) users.getRowData();
            }
            text = current.getEmail();
            albumController.deleteAllAlbumsOfUser(current);
            userRdf.deleteUser(current.getId());
            userDao.delete(current);
            if (fromList) {
                users.setWrappedData(userDao.findAll());
            }
        } 
        catch (SempicModelException ex) {
            SempicMessage.intance().errorMessage(ex.getMessage());
            return "failure";
        }
        if (session.isAdmin()){
            SempicMessage.intance().successDeleteMessage(current.getEmail());
            return "success_admin";
        }
        else {
            session.logout();
            SempicMessage.intance().successDeleteAccountMessage();
            return "success_user"; 
        }
    }
}

src/main/webapp/user/picture/create-picture.xhtml
<ui:composition template="/templates/layout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:h5="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:mp="http://primefaces.org/ui/material"
                xmlns:p="http://primefaces.org/ui">
    <f:metadata>
        <f:event listener="#{pictureController.accessPicture(event)}" type="preRenderView" />
        <f:viewParam name="albumId" value="#{pictureController.albumId}" />
    </f:metadata>
    <ui:define name="title">Création photo</ui:define>
    <ui:define name="content">
        <div class="row">
            <div class="col s6 offset-s3">
                <div class="card">
                    <div class="card-content">
                        <div class="left-align">
                            <h:form enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col s12 input-field">
                                        <div><h:outputLabel for="file" value="Image" /></div>
                                        <div>   
                                            <p:fileUpload id="file" value="#{pictureController.file}" fileUploadListener="#{pictureController.fileUploadListener}" update="messages"
                                                          mode="simple" required="true" requiredMessage="Le champs Fichier est obligatoire" sizeLimit="1000000" allowTypes="/(\.|\/)(gif|jpe?g|png)$/" >
                                                <f:validateRequired />
                                            </p:fileUpload>
                                            <p:growl id="messages" showDetail="true"/>
                                        </div>
                                    </div>
                                    <div class="col s12 input-field">
                                        <h:inputText id="description" value="#{pictureController.current.description}"/>
                                        <h:outputLabel for="description" value="Description" />
                                        <h:message for="description"/>
                                    </div>

                                    <div class="col s3 input-field">
                                        <button data-target="modal1" class="btn modal-trigger">
                                            <i class="medium material-icons">my_location</i>
                                            <span>Lieux</span>
                                        </button>
                                        <!-- Modal Structure -->
                                        <div id="modal1" class="modal">
                                            <div class="modal-content">
                                                <h4>Ajouter des lieux</h4>
                                                <div>
                                                    <p:chips id="place" value="#{pictureController.current.places}"/>
                                                    <h:message for="place"/>  
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="#!" class="modal-close waves-effect waves-green btn-flat">OK</a>
                                            </div>
                                        </div>
                                    </div>                      
                                    <div class="col s3 input-field">
                                        <button data-target="modal2" class="btn modal-trigger">
                                            <i class="medium material-icons">label</i>
                                            <span>Tags</span>
                                        </button>
                                        <div id="modal2" class="modal">
                                            <div class="modal-content">
                                                <h4>Ajouter des mots-clés</h4>
                                                <div>
                                                    <p:chips id="tags" value="#{pictureController.current.tags}"/>
                                                    <h:message for="tags"/>  
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="#!" class="modal-close waves-effect waves-green btn-flat">OK</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col s3 input-field">
                                        <button data-target="modal3" class="btn modal-trigger">
                                            <i class="medium material-icons">people</i>
                                            <span>Personnes</span>
                                        </button>
                                        <div id="modal3" class="modal">
                                            <div class="modal-content">
                                                <h4>Identifier des utilisateurs</h4>
                                                <div>
                                                    <p:selectManyCheckbox id="basic" value="#{pictureController.current.usersTagged}">
                                                        <f:selectItems value="#{userController.listUsers}" var="user" itemLabel="#{user.email}"/>
                                                    </p:selectManyCheckbox>
                                                    <h:message for="users"/> 
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="#!" class="modal-close waves-effect waves-green btn-flat">OK</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col s3 input-field">
                                        <h:inputText id="date" class="datepicker" value="#{pictureController.current.date}">
                                            <f:convertDateTime pattern="dd-MM-yyyy"/>  
                                        </h:inputText>
                                        <h:outputLabel for="date" value="Date"  />
                                        <h:message for="date"/>
                                    </div>
                                    <div class="center-align col s12 input-field">
                                        <h:commandButton id="submit" class="btn btn-medium" value="Créer" action="#{pictureController.create}"/>
                                    </div>
                                </div>
                            </h:form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/user/picture/update-picture.xhtml
<ui:composition template="/templates/layout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:h5="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    <f:metadata>
        <f:event listener="#{pictureController.accessPicture(event)}" type="preRenderView" />
        <f:viewParam name="pictureId" value="#{pictureController.pictureId}" />
    </f:metadata>
    <ui:define name="title">Modification image</ui:define>
    <ui:define name="content">
        <div class="row">
            <div class="col s6 offset-s3">
                <div class="card">
                    <div class="card-content">
                        <div class="left-align">
                            <h:form enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col s12 input-field">
                                        <p:graphicImage class="responsive-img" value="#{pictureController.current.mediumPath}" />
                                    </div>
                                    <div class="col s12 input-field">
                                        <h:inputText id="description" value="#{pictureController.current.description}"/>
                                        <p:outputLabel for="description" value="Description" />
                                        <h:message for="description"/>
                                    </div>
                                    <div class="col s3 input-field">
                                        <button data-target="modal1" class="btn modal-trigger">
                                            <i class="medium material-icons">my_location</i>
                                            <span>Lieux</span>
                                        </button>
                                        <!-- Modal Structure -->
                                        <div id="modal1" class="modal">
                                            <div class="modal-content">
                                                <h4>Ajouter des lieux</h4>
                                                <div>
                                                    <p:chips id="place" value="#{pictureController.current.places}"/>
                                                    <h:message for="place"/>  
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="#!" class="modal-close waves-effect waves-green btn-flat">OK</a>
                                            </div>
                                        </div>

                                    </div>                      
                                    <div class="col s3 input-field">
                                        <button data-target="modal2" class="btn modal-trigger">
                                            <i class="medium material-icons">label</i>
                                            <span>Tags</span>
                                        </button>
                                        <div id="modal2" class="modal">
                                            <div class="modal-content">
                                                <h4>Ajouter des mots-clés</h4>
                                                <div>
                                                    <p:chips id="tags" value="#{pictureController.current.tags}"/>
                                                    <h:message for="tags"/>  
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="#!" class="modal-close waves-effect waves-green btn-flat">OK</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col s3 input-field">
                                        <button data-target="modal3" class="btn modal-trigger">
                                            <i class="medium material-icons">people</i>
                                            <span>Personnes</span>
                                        </button>
                                        <div id="modal3" class="modal">
                                            <div class="modal-content">
                                                <h4>Identifier des utilisateurs</h4>
                                                <div>
                                                    <p:selectManyCheckbox id="basic" value="#{pictureController.current.usersTagged}">
                                                        <f:selectItems value="#{userController.listUsers}" var="user" itemLabel="#{user.email}"/>
                                                    </p:selectManyCheckbox>
                                                    <h:message for="users"/> 
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="#!" class="modal-close waves-effect waves-green btn-flat">OK</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col s3 input-field">
                                        <h:inputText id="date" class="datepicker" value="#{pictureController.current.date}">
                                            <f:convertDateTime pattern="dd-MM-yyyy"/>  
                                        </h:inputText>
                                        <h:outputLabel for="date" value="Date"  />
                                        <h:message for="date"/>
                                    </div>
                                    <div class="center-align col s6 input-field">
                                        <h:commandLink class="btn-floating btn-card blue btn-large" title="Enregistrer" action="#{pictureController.update}">
                                            <i class="medium material-icons">save</i>
                                        </h:commandLink>
                                    </div>
                                    <div class="center-align col s6 input-field">
                                        <h:commandLink class="btn-floating btn-card red btn-large" title="Supprimer" action="#{pictureController.delete}">
                                            <i class="medium material-icons">delete</i>
                                        </h:commandLink>
                                    </div>
                                </div>
                            </h:form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </ui:define>
</ui:composition>