src/main/java/fr/uga/miashs/sempic/entities/SempicPicture.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.miashs.sempic.entities;

import java.nio.file.Paths;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import fr.uga.miashs.sempic.SempicException;
import fr.uga.miashs.sempic.dao.PhotoStorage;
import java.io.IOException;
import java.io.Serializable;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Temporal;
import javax.validation.constraints.NotBlank;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 *
 * @author marty
 */
@Entity
@NamedQueries({
    @NamedQuery(
            name="query.SempicPicture.findAllOwned",
            query="SELECT p FROM SempicPicture p Join p.album a WHERE a.owner=:owner"),
    @NamedQuery(
            name = "query.SempicPicture.findAllOfAlbum",
            query = "SELECT p FROM SempicPicture p WHERE p.album=:album"),
    @NamedQuery(
            name = "query.SempicPicture.findAllPicturesFromIds",
            query = "SELECT p FROM SempicPicture p WHERE p.id IN :picturesIds"),})
public class SempicPicture implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    
    @ManyToOne
    private SempicAlbum album;

    @NotBlank(message = "Un nom de famille doit être donné")
    private String title;

    private String description;

    @LazyCollection(LazyCollectionOption.FALSE)
    @ElementCollection(targetClass = String.class)
    private List<String> places;

    @Temporal(javax.persistence.TemporalType.DATE)
    private Date date;

    @LazyCollection(LazyCollectionOption.FALSE)
    @ElementCollection(targetClass = String.class)
    private List<String> tags;

    @LazyCollection(LazyCollectionOption.FALSE)
    @ManyToMany
    private Set<SempicUser> usersTagged;
    
    public SempicPicture() {

    }

    public String getPicturePath() {
        return PhotoStorage.PICTURESTOREWEB.resolve(title).toString();
    }

    public String getThumbnailPath() throws SempicException {
        Path pic = Paths.get(title);

        try {
            PhotoStorage ps = new PhotoStorage(PhotoStorage.URLSTORE, PhotoStorage.URLTHUMBNAILSTORE);
            ps.getThumbnailPath(pic, 120);
            return PhotoStorage.buildAndVerify(PhotoStorage.THUMBNAILSSTOREWEB.resolve(String.valueOf(120)), pic).toString();
        } catch (IOException ex) {
            Logger.getLogger(SempicPicture.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";
    }

    public String getMediumPath() throws SempicException {
        Path pic = Paths.get(title);
        try {
            PhotoStorage ps = new PhotoStorage(PhotoStorage.URLSTORE, PhotoStorage.URLTHUMBNAILSTORE);
            ps.getThumbnailPath(pic, 400);
            return PhotoStorage.buildAndVerify(PhotoStorage.THUMBNAILSSTOREWEB.resolve(String.valueOf(400)), pic).toString();
        } catch (IOException ex) {
            Logger.getLogger(SempicPicture.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public SempicAlbum getAlbum() {
        return album;
    }

    public void setAlbum(SempicAlbum album) {
        if (album == null) {
            throw new NullPointerException("Album is null");
        }
        this.album = album;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<String> getPlaces() {
        if (places == null) {
            places = new ArrayList<>();
        }
        return places;
    }

    public void setPlaces(List<String> places) {
        this.places = places;
    }

    protected void addPlace(String place) {
        if (places == null) {
            places = new ArrayList<>();
        }
        places.add(place);
    }
    
    public List<String> getTags() {
        if (tags == null) {
            tags = new ArrayList<>();
        }
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Set<SempicUser> getUsersTagged() {
        return usersTagged;
    }

    public void setUsersTagged(Set<SempicUser> usersTagged) {
        this.usersTagged = usersTagged;
    }
    
   
    
    protected void addUsersTagged(SempicUser u) {
        if (usersTagged==null) {
            usersTagged = new HashSet<>();
        }
        usersTagged.add(u);
    }
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof SempicPicture)) {
            return false;
        }
        SempicPicture other = (SempicPicture) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "fr.uga.miashs.sempic.entities.SempicPicture[ id=" + id + " ]";
    }

}

src/main/java/fr/uga/miashs/sempic/entities/SempicUser.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.miashs.sempic.entities;

import java.io.Serializable;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.validation.constraints.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Jerome David <jerome.david@univ-grenoble-alpes.fr>
 */
@Table(uniqueConstraints = {
    @UniqueConstraint(name = "UniqueEmail", columnNames = {"email"})
})
@NamedQueries({
    @NamedQuery(
            name = "query.SempicUser.findAllEager",
            query = "SELECT DISTINCT u FROM SempicUser u LEFT JOIN FETCH u.groups LEFT JOIN FETCH u.memberOf"
    ),
    @NamedQuery(
            name = "query.SempicUser.readByEmail",
            query = "SELECT DISTINCT u FROM SempicUser u WHERE u.email=:email "
    ),
    @NamedQuery(
            name = "query.SempicUser.login",
            query = "SELECT DISTINCT u FROM SempicUser u WHERE u.email=:email AND u.passwordHash=:passwordHash"
    )
})
@NamedEntityGraph(
        name = "graph.SempicUser.groups-memberOf",
        attributeNodes = {
            @NamedAttributeNode("groups"),
            @NamedAttributeNode("memberOf"),}
)

@Entity
@XmlRootElement
@XmlAccessorType(XmlAccessType.PUBLIC_MEMBER)
public class SempicUser implements Serializable {

    public final static String PREFIX = "/users/";

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    @NotBlank(message = "Un nom de famille doit être donné")
    private String lastname;

    @NotBlank(message = "Un prénom doit être donné")
    private String firstname;

    @Email
    @NotBlank(message = "Une adresse mail doit être donnée")
    private String email;

    @NotBlank(message = "Un mot de passe doit être donné")
    private String passwordHash;

    @Transient
    private transient String password;

    @OneToMany(mappedBy = "owner", cascade = CascadeType.REMOVE, fetch = FetchType.EAGER)
    private Set<SempicGroup> groups;

    @ManyToMany(mappedBy = "members", cascade = CascadeType.REMOVE, fetch = FetchType.EAGER)
    private Set<SempicGroup> memberOf;

    @OneToMany(mappedBy = "owner", cascade = CascadeType.REMOVE, fetch = FetchType.EAGER)
    private Set<SempicAlbum> albums;

    @Enumerated(EnumType.STRING)
    @Column(columnDefinition = "VARCHAR(5)")
    private SempicUserType userType;

    @ManyToMany(mappedBy = "usersTagged", cascade = CascadeType.REMOVE, fetch = FetchType.EAGER)
    private Set<SempicPicture> picturesTagged;

    public SempicUser() {
        userType = SempicUserType.USER;
    }

    @XmlID
    @XmlAttribute(name = "id")
    public String getIdUri() {
        return "users/" + getId();
    }

    public long getId() {
        return id;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getFullName() {
        return lastname + " " + firstname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @XmlTransient
    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public void setPassword(String p) {
        password = p;
    }

    @XmlTransient
    public String getPassword() {
        return password;
    }

    @XmlIDREF //permet de récupérer seulement l'id du group
    public Set<SempicGroup> getGroups() {
        if (groups == null) {
            return Collections.emptySet();
        }
        return Collections.unmodifiableSet(groups);
    }

    @XmlIDREF
    public Set<SempicGroup> getMemberOf() {
        if (memberOf == null) {
            return Collections.emptySet();
        }
        return Collections.unmodifiableSet(memberOf);
    }

    @XmlIDREF
    public Set<SempicPicture> getPicturesTagged() {
        if (picturesTagged == null) {
            return Collections.emptySet();
        }
        return Collections.unmodifiableSet(picturesTagged);
    }

    public SempicUserType getUserType() {
        return userType;
    }

    public void setUserType(SempicUserType userType) {
        this.userType = userType;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 97 * hash + (int) (this.id ^ (this.id >>> 32));
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SempicUser other = (SempicUser) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

    public Set<SempicAlbum> getAlbums() {
        return albums;
    }

    public void setAlbums(Set<SempicAlbum> albums) {
        this.albums = albums;
    }

    protected void addAlbum(SempicAlbum a) {
        if (albums == null) {
            albums = new HashSet<>();
        }
        albums.add(a);
    }

    @Override
    public String toString() {
        return "SempicUser{id=" + id + ", "
                + "lastname=" + lastname + ", firstname=" + firstname + ", email=" + email + '}';
    }
}

src/main/java/fr/uga/miashs/sempic/backingbeans/AlbumController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.miashs.sempic.backingbeans;


import fr.uga.miashs.sempic.SempicException;
import fr.uga.miashs.sempic.SempicMessage;
import fr.uga.miashs.sempic.SempicModelException;
import fr.uga.miashs.sempic.SempicModelUniqueException;
import fr.uga.miashs.sempic.dao.AlbumFacade;
import fr.uga.miashs.sempic.dao.SempicUserFacade;
import fr.uga.miashs.sempic.entities.SempicAlbum;
import fr.uga.miashs.sempic.entities.SempicPicture;
import fr.uga.miashs.sempic.entities.SempicUser;
import fr.uga.miashs.sempic.rdf.AlbumStore;
import fr.uga.miashs.sempic.util.AccessRedirect;
import java.io.IOException;
import java.io.Serializable;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import javax.annotation.PostConstruct;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;


/**
 *
 * @author Jerome David <jerome.david@univ-grenoble-alpes.fr>
 */
@Named
@ViewScoped
public class AlbumController implements Serializable {

    private SempicAlbum current;

    @Inject
    private SessionTools session;
    
    @Inject
    private AlbumFacade albumDao;

    @Inject
    private SempicUserFacade userDao;
    
    private AlbumStore albumRdf;

    @Inject
    private PictureController pictureController;

    private DataModel<SempicAlbum> albums;
        
    public AlbumController() {
        userDao = new SempicUserFacade();
        albumDao = new AlbumFacade();
        albumRdf = new AlbumStore();
    }

    @PostConstruct
    public void init() {
        current = new SempicAlbum();
    }
    
    public void accessAlbum(ComponentSystemEvent event) throws IOException{
        if (current == null || (!current.getOwner().equals(session.getConnectedUser()) && !session.isAdmin())) {
          AccessRedirect.intance().redirectAccessDenied();
        }
    }
    
    public List<SempicUser> getUsers() {
        return userDao.findAll();
    }
    
    public void setOwnerId(String id) {
        current.setOwner(userDao.read(Long.valueOf(id)));
    }
    
    public String getOwnerId() {
        if (current.getOwner()==null)
            return "-1";
        return ""+current.getOwner().getId();
    }
    
    
    public void setAlbumId(String id) {
        current = albumDao.read(Long.valueOf(id));
    }

    public String getAlbumId() {
        if (current == null) {
            return "-1";
        }
        return "" + current.getId();
    }    
    public SempicAlbum getCurrent() {
        return current;
    }

    public void setCurrent(SempicAlbum current) {
        this.current = current;
    }
    
    public DataModel<SempicAlbum> getAlbums() throws SempicModelException {
        if (albums == null) {
            if (session.isAdmin()){
                albums = new ListDataModel<>(albumDao.findAll());
            }
            else {
                albums = new ListDataModel<>(albumDao.findAllOfOwner(session.getConnectedUser()));
            }
        }
        return albums;
    }
    
    public Set<SempicPicture> getPictures(){
            return current.getPictures();
    }
    
    public String create() {
        try {
            albumDao.create(current);
            albumRdf.createAlbum(current.getId(), current.getOwner().getId(), current.getTitle(), current.getDescription());
        } catch (SempicModelException ex) {
            SempicMessage.intance().errorMessage(ex.getMessage());
            return "failure";
        }
        SempicMessage.intance().successCreateMessage(current.toString());
        return "success";
    }
        
    
    public String update() {        
        try {
            albumDao.update(current);
        } 
        catch (SempicModelUniqueException ex) {
            SempicMessage.intance().errorMessage("Un album avec ce nom existe déjà");
            return "failure";
        }
        catch (SempicModelException ex) {
            SempicMessage.intance().errorMessage(ex.getMessage());
            return "failure";
        }
        SempicMessage.intance().successUpdateMessage(current.toString());
        return "success";
    }
    
    public String delete() throws IOException, SempicException {
        String text;
        Boolean fromList = false;
        try {
            if (current.getTitle() == null){
                fromList = true;
                current = (SempicAlbum) albums.getRowData();
            }
            text = current.toString();
            pictureController.deleteAllPicturesOfAlbum(current);
            current.setPictures(Collections.emptySet());
            albumRdf.deleteAlbum(current.getId());
            albumDao.delete(current);
            if (fromList) {
                albums.setWrappedData(albumDao.findAll());
            }
        } 
        catch (SempicModelException ex) {
            SempicMessage.intance().errorMessage(ex.getMessage());
            return "failure";
        }
        SempicMessage.intance().successDeleteMessage(text);	
        return "success";
    }
    
    public void deleteAllAlbumsOfUser(SempicUser user) throws IOException, SempicException {
        for (SempicAlbum album : user.getAlbums()) {
           current = album;
           delete();
        }
    }
  
}

src/main/webapp/create-user.xhtml
<ui:composition template="/templates/layout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h5="http://xmlns.jcp.org/jsf/passthrough">

    <ui:define name="title">Création utilisateur</ui:define>
    <ui:define name="content">
        <div class="row">
            <div class="col s6 offset-s3">
                <div class="card">
                    <div class="card-content">
                        <div class="left-align">
                            <h:form enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col s6 input-field">
                                        <h:inputText id="lastname" value="#{userController.current.lastname}" required="true" requiredMessage="Le champ Nom est requis" />
                                        <h:outputLabel for="lastname" value="Nom"  />
                                    </div>
                                    <div class="col s6 input-field">
                                        <h:inputText id="firstname" value="#{userController.current.firstname}" required="true" requiredMessage="Le champ Prénom est requis" />
                                        <h:outputLabel for="firstname" value="Prénom"  />
                                    </div>
                                    <div class="col s12 input-field">
                                        <h:inputText id="email" value="#{userController.current.email}" h5:type="email" required="true" requiredMessage="Le champ Email est requis" />
                                        <h:outputLabel for="email" value="Email"  />
                                    </div>
                                    <div class="col s12 input-field">
                                        <h:inputSecret id="password" value="#{userController.current.password}" required="true" requiredMessage="Le champ Mot de passe est requis" />
                                        <h:outputLabel for="password" value="Mot de passe"  />
                                    </div>                                
                                    <div class="center-align col s12 input-field">
                                        <h:commandButton value="Créer" action="#{userController.create}" id="submit" class="btn btn-large" />
                                    </div>
                                </div>
                            </h:form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/home.xhtml
<ui:composition template="/templates/layout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h5="http://xmlns.jcp.org/jsf/passthrough">

    <ui:define name="metadata"><f:viewAction  action="home"/></ui:define>
    <ui:define name="title">Recherche</ui:define>
    <ui:define name="content">
        <div class="row">
            <div class="col s12">
                <h:form>
                    <div class="row">
                        <div class="input-field col s3">
                            <p:autoComplete                                 
                                id="users"
                                h5:placeholder="Utilisateur"  
                                completeMethod="#{searchController.completeUserContains}"
                                var="user"
                                value="#{searchController.searchUserId}"
                                itemLabel="#{user.fullName}" 
                                itemValue="#{user.id}" 
                                forceSelection="true"
                                >
                                <p:ajax event="itemSelect" listener="#{searchController.handleSelect}" />
                                <p:column>
                                    <i class="medium material-icons">account_circle</i>
                                </p:column>
                                <p:column>
                                    <h:outputText value="#{user.fullName}" />
                                </p:column>
                            </p:autoComplete>
                        </div>
                        <div class="input-field col s3">
                            <p:inputText id="place" h5:placeholder="Lieu" value="#{searchController.searchPlace}" />
                        </div>
                        <div class="input-field col s3">
                            <p:inputText id="search" h5:placeholder="Mot clé" value="#{searchController.searchWord}" />
                        </div>
                        <div class="input-field col s2">
                            <h:inputText id="date" h5:placeholder="Date" class="datepicker" value="#{searchController.searchDate}">
                                <f:convertDateTime pattern="dd-MM-yyyy"/>  
                            </h:inputText>
                        </div>
                        <div class="input-field col s1">
                            <p:commandLink class="mdl-navigation__link" title="Rechercher" action="#{searchController.search()}" update="pictures">
                                <i class="medium material-icons">search</i>
                            </p:commandLink>
                        </div>
                    </div>
                   
                    <div class="row">
                         <h:panelGroup rendered="#{sessionTools.admin}" >
                        <div class="input-field col s3">
                            <div>Mes photos uniquement</div>
                            <div class="switch">
                                <label>
                                    Non
                                    <h:selectBooleanCheckbox value="#{searchController.searchOnlyPicturesUser}" />
                                    <span class="lever"></span>
                                    Oui
                                </label>
                            </div>
                        </div>
                    </h:panelGroup>
                        <div class="input-field col s8">
                            <ul class="collapsible">
                                <li>
                                    <div class="collapsible-header"><i class="material-icons">filter_list</i>Filtre Avancé</div>
                                    <div class="collapsible-body">
                                        <h:selectOneMenu  value="#{searchController.annotationsFilter.entrySet()}" class="browser-default" >
                                            <f:selectItem itemValue="#{null}" itemLabel="-- Choisissez votre option --" />
                                            <f:selectItems value="#{searchController.annotationsFilter.entrySet()}" var="entry" itemValue="#{entry.key}" itemLabel="#{entry.value}" />
                                        </h:selectOneMenu>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div id="portfolio" class="section gray">
                            <div class="container">
                                <div class="gallery row">
                                    <h:panelGroup id="pictures">
                                        <h:outputText rendered="#{empty searchController.pictures}" value="Aucune photo disponible" />
                                        <ui:repeat value="#{searchController.pictures}" var="picture" rendered="#{not empty searchController.pictures}">
                                            <div class="col l4 m6 s12 thumbnail-medium">
                                                <h:graphicImage class="materialboxed" value="#{picture.mediumPath}" />
                                            </div>
                                        </ui:repeat>
                                    </h:panelGroup>
                                </div>
                            </div>
                        </div>
                    </div>
                </h:form>
            </div>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/login-error.xhtml
<ui:composition template="/templates/layout.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">
    
    <ui:define name="title">Utilisateur Inconnu</ui:define>
    <ui:define name="content">
        <div>Adresse email et mot de passe inconnus. Veuillez réessayer</div>
    </ui:define>
</ui:composition>

src/main/webapp/login.xhtml
<ui:composition template="/templates/layout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h5="http://xmlns.jcp.org/jsf/passthrough">

    <ui:define name="title">Utilisateur</ui:define>
    <ui:define name="content">
        <div class="row">
            <div class="col s5">
                <h2>Connexion</h2>
                <div class="card">
                    <div class="card-content">
                        <div class="left-align">
                            <h:form id="login" onsubmit="document.getElementById('login').action = 'j_security_check';" prependId="false">
                                <div class="row">
                                    <div class="col s12 input-field">
                                        <h:inputText id="j_username" required="true" requiredMessage="Identifiant requis"/>
                                        <h:outputLabel for="j_username" value="Username"  />
                                    </div>
                                    <div class="col s12 input-field">
                                        <h:inputSecret id="j_password" required="true" requiredMessage="Mot de passe requis"/>
                                        <h:outputLabel for="j_password" value="Password" />
                                    </div>
                                    <div class="center-align col s12 input-field">
                                        <h:commandButton id="submit" class="btn btn-medium" value="Connexion" />
                                    </div>
                                </div>
                            </h:form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col s7">
                <h2>Inscription</h2>
                <div class="card">
                    <div class="card-content">
                        <div class="left-align">
                            <h:form >
                                <div class="row">
                                    <div class="col s6 input-field">
                                        <h:inputText id="lastname" value="#{userController.current.lastname}" required="true" requiredMessage="Le champ Nom est requis" />
                                        <h:outputLabel for="lastname" value="Nom"  />
                                    </div>
                                    <div class="col s6 input-field">
                                        <h:inputText id="firstname" value="#{userController.current.firstname}" required="true" requiredMessage="Le champ Prénom est requis" />
                                        <h:outputLabel for="firstname" value="Prénom"  />
                                    </div>
                                    <div class="col s12 input-field">
                                        <h:inputText id="email" value="#{userController.current.email}" h5:type="email" required="true" requiredMessage="Le champ Email est requis" />
                                        <h:outputLabel for="email" value="Email"  />
                                    </div>
                                    <div class="col s12 input-field">
                                        <h:inputSecret id="password" value="#{userController.current.password}" required="true" requiredMessage="Le champ Mot de passe est requis" />
                                        <h:outputLabel for="password" value="Mot de passe"  />
                                    </div>                                
                                    <div class="center-align col s12 input-field">
                                        <h:commandButton value="Inscription" action="#{userController.create}" id="submit" class="btn btn-medium"/>
                                    </div>
                                </div>
                            </h:form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </ui:define>
</ui:composition>